falcosecurity/charts

falco/.helmignore
falco/CHANGELOG.md
falco/Chart.yaml
falco/OWNERS
falco/README.md
falco/ci/ebpf-values.yaml
falco/rules/application_rules.yaml
falco/rules/falco_rules.local.yaml
falco/rules/falco_rules.yaml
falco/rules/k8s_audit_rules.yaml
falco/templates/NOTES.txt
falco/templates/_helpers.tpl
falco/templates/auditsink.yaml
falco/templates/clusterrole.yaml
falco/templates/clusterrolebinding.yaml
falco/templates/configmap-rules.yaml
falco/templates/configmap.yaml
falco/templates/daemonset.yaml
falco/templates/deployment.yaml
falco/templates/podsecuritypolicy.yaml
falco/templates/secret-certs.yaml
falco/templates/secret.yaml
falco/templates/service.yaml
falco/templates/serviceaccount.yaml
falco/values.yaml

This pulls in the falco helm chart from the charts repo under helm. Helm has asked maintainers to take these steps.
Add 'falco/' from commit '5ef70d45258bb36cba453065427e8c6a6284c90f'
Commands run:
(from helm/charts)
git subtree  split --prefix stable/falco/
git co <resulting sha>
git co -b falco_split
(from falcosecurity/charts)
git subtree add --prefix falco ../charts falco_split
git-subtree-dir: falco
git-subtree-mainline: 26466a22e5640cbd559aa7f87882d729191105cc
git-subtree-split: 5ef70d45258bb36cba453065427e8c6a6284c90f
Signed-off-by: Spencer Krum <nibz@spencerkrum.com>

Pull falco chart from helm/charts

---

README.md
release.sh

This pull request sets us up for creating our own helm hub and release pipeline. It also needs a few things:
1) Use this branch as a template for creating our own `gh-pages` branch: <https://github.com/nibalizer/charts/tree/import_gh_pages>
2) Enable Github Pages in the Settings
3) Until automation is set up, manual releases require a specific directory structure (outlined in `release.sh`)
After those things are in place we'll have a repo that [looks like this](https://nibalizer.github.io/charts/). That can be used today with:
```bash
helm repo add nibz https://nibalizer.github.io/charts/
helm search repo | grep falco
helm install falco nibz/falco
```
In the future `falcosecruity` will replace the other words.

Set up releases and helm hub

---

README.md
falco/Chart.yaml
falco/README.md
release.sh

This PR includes some fixes to make the temporary release process works properly.
It also corrects the instructions to use the newly published chart.
An example of outcome (produced by the release process) is here https://github.com/falcosecurity/charts/pull/18
/kind bug
/cc @fntlnz
/cc @leodido
/cc @nibalizer

fix: temporary release process

---

falco/CHANGELOG.md
falco/templates/clusterrole.yaml

Porting [this fix](https://github.com/falcosecurity/falco/pull/1136) to the chart.
/kind bug
/cc @fntlnz

fix(falco): add missing privileges for the apps Kubernetes API group

---

falco/CHANGELOG.md
falco/Chart.yaml

This release introduces small changes (see the [changelog](https://github.com/falcosecurity/charts/compare/release/falco-1.1.10?expand=1#diff-fe5da4546bd141b139a070e83b4930b3R8)) and is mainly intended to test the new releasing automation.

release(falco): 1.1.20

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
falco/templates/securitycontextconstraints.yaml
falco/values.yaml

/kind feature
The daemonset fails to create the pods in Openshift environment due to the request of elevated privileges, like HostPath mounts, privileged: true, etc.
This PR adds a SCC resource which is only created in Openshift (detected via API capabilities in the chart), and that can be disabled with scc.create: false in the values.yaml
**Checklist**

Add SCC to support Openshift

---

falco/rules/falco_rules.yaml

/kind bug
Prevent warning message from falco when booting falco itself. Below is a sample message :
```
Warning Pod started with privileged container (user=system:serviceaccount:kube-system:daemon-set-controller pod=falco-42brw ns=monitoring images=docker.io/falcosecurity/falco:0.24.0)
```

Add 'docker.io/falcosecurity/falco' image to 'falco_privileged_images' macro

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/servicemonitor.yaml
falco-exporter/values.yaml

/kind feature
This PR adds the capability to deploy a Prometheus Operator Service Monitor together with the Exporter.
**Checklist**

[Faclo-exporter]Added Prometheus Service Monitor to helm chart

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/configmap.yaml
falco/templates/daemonset.yaml
falco/values.yaml

/kind bug
This PR follows up the discussion I had with @nibalizer on https://github.com/falcosecurity/charts/pull/55
Basically, this PR moves the shared-pipe to the `/tmp/shared-pipe` folder (an emptyDir), so it will not conflict with `/var/run/falco` (used for the gRPC unix socket) as described in #54
Fixes #54
In the future, I believe the best option is to clean up integrations from here, as pointed out in [this comment](https://github.com/falcosecurity/charts/pull/55#issuecomment-663730694).
Meanwhile, we make a decision about integrations, I think it …

chore(falco): move shared-pipe to tmp

---

falco-exporter/README.md

The Falco chart (instead of the falco-expoter chart) was used in an example within the README.md. This can lead people to confusion. This PR just fixes this small issue.

docs(falco-exporter): use falco-exporter in the example

---

falcosidekick/Chart.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/values.yaml

Signed-off-by: Armin armin@coralic.nl
What type of PR is this?
/kind feature
Any specific area of the project related to this PR?
/area helm
What this PR does / why we need it:
Adding the imagePullSecrets to the Helm deployments to allow authenticated Docker registries.

Add imagePullSecretes to the Helm chart

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/values.yaml

/kind feature
A pod security context is useful in EKS when we want to mount the ServiceAccount token and use it to get our AWS credentials. Without the fsGroup, the ServiceAccount token is not accessible in the container.
**Checklist**

Configure the pod security context in the Falco Sidekick Deployment

---

falcosidekick/values.yaml

Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
> /kind bug
/kind cleanup
> /kind design
Updates the image from 2.13 to 2.14.
Without this, discord output is not included
Fixes #
**Checklist**

Update falcosidekick default image to most recent release

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/_helpers.tpl
falco-exporter/templates/daemonset.yaml
falco-exporter/templates/podsecuritypolicy.yaml
falco-exporter/templates/role.yaml
falco-exporter/templates/rolebinding.yaml
falco-exporter/templates/service.yaml
falco-exporter/templates/serviceaccount.yaml
falco-exporter/values.yaml

/kind feature
This PR implements the possibility to automatically create a proper working PSP, Role and RoleBinding for a Helm based falco-exporter deployment. It also fixes the namespace assignment of the falco-exporter Service and ServiceAccount object which would not have been assigned to a specific namespace.
Fixes https://github.com/falcosecurity/charts/issues/103
I also made a new release `v0.3.5` with the regarding release nodes. The deployment was tested on Minikube `v1.13.0` with the following commands:
```bash
⋊> ~/G/charts on master ◦ k …
```

falco-exporter: Added podSecurityPolicy configuration values

---

.circleci/release.sh

/kind bug
It happened several times that the release job failed just because the release was not found by GitHub API immediately after it had been created.
Some examples from the CI logs:
https://app.circleci.com/pipelines/github/falcosecurity/charts/120/workflows/fb349a0a-0f37-4ce7-b666-64854990aa6d/jobs/112
https://app.circleci.com/pipelines/github/falcosecurity/charts/120/workflows/9e467708-649a-463f-af0c-732b213b06a0/jobs/110
https://app.circleci.com/pipelines/github/falcosecurity/charts/114/workflows/bb91e320-84f4-4726-a365-93bafeaf8f30/jobs/105
Then I noticed that even though the logs reported:
```
Successfully packaged chart and saved it to: …
```

fix(build): wait for releases to be ready

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/role.yaml
falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/clusterrole.yaml
falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/clusterrole.yaml
falcosidekick/templates/ingress.yaml

Deprecation Info:
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>
/kind bug
**Checklist**

Replace extensions apiGroup/apiVersion because of deprecation

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/clusterrole.yaml
falco/templates/deployment.yaml
falco/templates/podsecuritypolicy.yaml

Fixes #128
Signed-off-by: Christian Zunker <christian.zunker@codecentric.cloud>
/kind bug
The enabled the fake generator deployment in a PSP enabled cluster.
Fixes #128
**Checklist**

Add PSP support to fake event generator

---

falco/Chart.yaml
falco/ci/ci-values.yaml

If install Falco using the default configuration it will try to install the kernel module which is not available in CI, to avoid any issues we can use a custom value to test on CI.
The custom value sets the `--userspace` and with that does not install the kernel module
None
**Checklist**

falco/ci: Set values to deploy falco on ci

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/grafana-dashboard.yaml
falco-exporter/values.yaml

Signed-off-by: Toni Tauro <toni.tauro@adfinis.com>
/kind bug
Adds an additional Value for defining the PrometheusDatasource name to be used in the grafana Dashboard. This makes sure that Grafana can import the dashboard and references the Datasource correctly.
* Removes the unneeded `input` object
* adds the needed `templating` object as suggested by @jemag [comment](https://github.com/falcosecurity/charts/issues/109#issuecomment-738932242)
#109 
Fixes #109 
First PR @falcosecurity
**Checklist**

fix(#109): grafana Dashboard prometheus datasource name

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
falco/templates/daemonset.yaml
falco/values.yaml

/kind feature
This PR makes it possible to add additional volumes and volumeMounts to the falco daemonset. In my particular use-case, I might want to mount optional rules from an existing configMap.
N/A
N/A
**Checklist**

feat(falco): allow adding additional volumes and volumeMounts to falco daemonset

---

falco/.gitignore
falco/CHANGELOG.md
falco/Chart.lock
falco/Chart.yaml
falco/README.md
falco/templates/NOTES.txt
falco/templates/configmap.yaml
falco/values.yaml

> /kind bug
> /kind design
/kind feature
This PR adds `falcosidekick` chart as an optionnal dependency for `falco` chart. It means we can deploy together `falco` and `falcosidekick`.
A message at end of deployment of `falco` has also been added for promoting usage of `falcosidekick` and …

add falcosidekick as optional dependency for falco

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/grafana-dashboard.yaml

/kind bug
Adjust Grafana dashboard to only show events with non-zero rate.
Currently where there are large numbers of alerts that have previously fired, these are exported to Prometheus and therefore show in the graph legend making it difficult to read.
With this change, alerts now only shows in the legend if they have occurred within the time range for the dashboard.
**Checklist**

Only show non-zero rates in Grafana

---

falco/CHANGELOG.md
falco/Chart.yaml

The previous location specified for the icon is returning a 404
not found error. The new location is where the CNCF keeps the
artwork.
This was noticed on the artifact hub as it was no longer able to
pull the image.
/kind bug
Fixes #192
**Checklist**

Updating the location of the falco icon

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/rules/falco_rules.yaml

The desc of the rule `Write below monitored dir` have a typo.
https://github.com/falcosecurity/charts/blob/master/falco/rules/falco_rules.yaml#L1027
> /kind bug
fix typo.
none
**Checklist**

fix: update rule description

---

index.html

/area gh-pages
This small PR adds link to this repo `README` file, for up-to-date information about which charts are available, instead of listing only the Falco chart.

Add link on GH Pages to charts' repo Readme

---

.circleci/config.yml

/kind bug
Those jobs are not expected to run on the [gh-pages](https://github.com/falcosecurity/charts/tree/gh-pages) branch
Fixes #
**Checklist**

build(.circleci): do not run charts job on `gh-pages` branch

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/templates/secrets.yaml

/kind bug
The statsd config options not being correctly set in the secret.
It also adds a [config checksum](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments) to the deployment pods, so that on config change falco sidekick will restart.
**Checklist**

fix falcosidekick statsd config in secret

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/daemonset.yaml

/kind bug
falco: fix port for livenessProbe and readinessProbe
my bad, did not realize the port name HTTP does not exist, maybe we can add a name to it
Fixes https://github.com/falcosecurity/charts/issues/235
**Checklist**

falco: fix port for livenessProbe and readinessProbe

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/deployment-ui.yaml

/kind bug
Adds `imagePullSecrets` to `deployment-ui.yaml` allowing to pull the image from a private repo with authentication.
The key `imagePullSecrets` are configurable within the values, but not evaluated within the `deployment-ui.yaml` template.
**Checklist**

Add missing imagePullSecrets in falcosidekick/templates/deployment-ui.yaml

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/daemonset.yaml

Signed-off-by: Erwan Miran <mirwan666@gmail.com>
/kind bug
When `falco.webserver.sslEnabled` is true, readiness and liveness probes fail as performed with http scheme (default)
None that I know of
I didn't check the "Variables are documented in the README.md" item as no change has been made. Don't know if that was wrong...
**Checklist**

Fix readiness and liveness probes scheme when ssl is enabled

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/secrets.yaml

Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>
/kind feature
Fixes #
**Checklist**

Updated secrets for Fission output

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/_helpers.tpl
falcosidekick/templates/ingress-ui.yaml
falcosidekick/templates/ingress.yaml
falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
Fixes #273
```
$ helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
```
Kubernetes <= 1.17:
```
$ helm template …
```

feat(falcosidekick)!: support Ingress API version networking.k8s.io/v1

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/secrets.yaml

Signed-off-by: Chase Martin <8998243+chasestech@users.noreply.github.com>
/kind bug
When installing/upgrading the falcosidekick Helm chart, an error is thrown due to duplicated `FISSION_*` keys in the secrets.yaml file. 
Fixes #
**Checklist**

Remove duplicate Fission keys in secret

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/daemonset.yaml

/kind bug
This fixes the escaping for the `FALCO_K8S_NODE_NAME` value, which passed a broken node name when using the `--k8s-node` cli parameter. This has been reported here 👉🏼  https://github.com/falcosecurity/falco/issues/1786
The version has been bumped to `1.16.1` to reflect the new change.

fix(falco): correctly escape FALCO_K8S_NODE_NAME

---

falco-exporter/Chart.yaml
falco-exporter/templates/role.yaml
falco-exporter/templates/rolebinding.yaml

/kind bug
> /kind design
The `namespace` key was specified twice in the role/rolebindings which are created if PSPs are enabled. This means that the chart couldn't be applied by flux with an error like this:
```
✗ HelmRelease reconciliation failed: Helm upgrade failed: error while running post render on files: …
```

Fix duplicate namespace keys in role/rolebinding

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/prometheusrule.yaml

/kind bug
/kind cleanup
Fixes this error:
```
The  "prometheusrules" is invalid: : 49:11: group "falco-exporter", rule 1, "FalcoExporterAbsent": could not parse expression: 1:31: parse error: unexpected character inside braces: ')'
```
**Checklist**
Signed-off-by: Lucas Bickel <lucas.bickel@adfinis.com>

fix(falco-exporter): fix FalcoExporterAbsent rule

---

falco/CHANGELOG.md
falco/Chart.yaml

Use the latest version of the falcosidekick chart when deploying it with falco. It is needed for newer kubernetes clusters (> 1.18) for example
None
**Checklist**

Update falcosidekick dependency

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/daemonset.yaml

Signed-off-by: Thomas Spear <tspear@conquestcyber.com>
/kind bug
> /kind design
Some kubernetes instances may pass along the quotes in a YAML list when the list item does not start with the double quotes, and this syntax causes issues with the new node hostname check as described below.
The falco-no-driver …

Fix quoting issue in falco chart daemonset template

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
falco/templates/configmap.yaml
falco/values.yaml

/kind bug
When including the Falco helm chart inside a parent chart, that messes with the way the falcosidekick Service name gets generated, which in turn means falco can't send notifications. A user might expect that they could override this behavior by setting `falco.httpOutput.url` but currently that value is ignored if falcosidekick is enabled.
This PR fixes that issue by always allowing `falco.httpOutput.url` to override the auto-generated URL.
Fixes #280
Quick way to test:
```
$ cd …
```

Make falco.httpOutput.url always take precedence. Fixes #280

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/configmap.yaml

/kind bug
In #320, I used the yaml pipe operator to have a multi-line string, but that preserves a trailing newline which seemed to be messing up falco. This PR fixes that by using single quotes (no newlines).
Test:
```
$ helm template . --set falcosidekick.enabled=true --set falco.httpOutput.url=http://customurl | grep -A 3 "http_output"
http_output:
enabled: true
url: 'http://customurl'
user_agent: falcosecurity/falco
$ helm template . --set falcosidekick.enabled=true | grep -A 3 "http_output"
http_output:
enabled: true
url: 'http://RELEASE-NAME-falco-falcosidekick:2801'
user_agent: falcosecurity/falco
``` …

Fix whitespace around http_output url

---

tests/e2e-kind.sh
tests/kind-config.yaml

/kind bug
> /kind design
Our integration tests use `kind`. Currently, the CI is broken because the `kind` version we were using is not working anymore on our CI. This PR bumps to the latest `kind` version and solve the issue.
Fixes #
I'll …

build(tests): bump kind version

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/OWNERS

/kind cleanup
For https://github.com/falcosecurity/falco/issues/2115, this PR proposes moving inactive approvers (who had very little or zero contributions over the past 6 months) from `approvers` to `emeritus_approvers` in OWNERS.
This is part of https://github.com/falcosecurity/charts/pull/360, that was split due to the required chart version bump.

update(falco/OWNERS): move inactive approvers to emeritus_approvers

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/templates/pod-template.tpl
falco/values.yaml

Signed-off-by: Tsubasa Nagasawa <toversus2357@gmail.com>
/kind feature
We would like to add extra environment variables (e.g. HTTP/HTTPS proxy env) to driver loader.
None.
**Checklist**

feat(falco): Add ability to specify extra env to driver loader initContainer

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/pod-template.tpl
falco/values.yaml

/kind bug
/kind feature
When Falco is deployed without the syscall data source enabled (e.g. as Deployment for K8s audit events), it still mounts `/proc` by default, which often violates security policies (e.g. PSPs). 
When `/proc` would only be mounted when it's really required, the Falco Pod would not require a separate security policy handling whenever Falco is only configured to receive K8s audit events (or events from other plugins). Therefore, I propose to only mount it, whenever `.Values.driver.enabled` is set to `true` (so basically "by default"). To override this new default behaviour, the `mounts.enforceProcMount` …

Added `mounts.enforceProcMount` flag

---

OWNERS
falco/Chart.yaml
falco/OWNERS

This supersedes #373 due to it being not mergeable. See https://github.com/falcosecurity/falco/issues/2143#issuecomment-1195195353.
/cc @falcosecurity/charts-maintainers

update(OWNERS): remove nestorsalceda

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/values.yaml

```
```
> /kind bug
> /kind design
/kind feature
The default configuration for the `ebpf probe` uses the following configuration values `.Values.driver.ebpf.hostNetwork=true` and `.Values.driver.ebpf.leastPrivileged=true`. 
`hostNetwork=true` is needed to …

update(falco): deploy falco in privileged mode when using ebpf probe

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/templates/certs-secret.yaml

```
```
/kind bug
> /kind design
When using the 'with' keyword to change the scope we can not access the global variables using the `.` notation. We must use the `$` variable which is always global and will point to the root context. …

fix(falco): correctly point to the root context inside a local scope

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/pod-template.tpl

/kind bug
The `falco-no-driver` image was unable to start when the eBPF probe was used because the Falco Pod did not have access to the host's `/sys/kernel/debug`. However, this path would be required to load the tracepoints.
Fixes https://github.com/falcosecurity/falco/issues/2145
**Special notes for your reviewer**: CC @Andreagit97 
**Checklist**

Fix debugfs mount when `falco-no-driver` image and ebpf driver is used

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/clusterrole.yaml
falco/templates/clusterrolebinding.yaml
falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/rbac.yaml

/kind bug
This PR removes `namespace` definition in `ClusterRole` and `ClusterRoleBinding` metadata.
`namespace` definition gets omitted once the resources are applied, therefore after after each build and apply these resources are changed.
None
**Checklist**

fix: remove `namespace` from `clusterrole` and `clusterrolebinding` metadata

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/podsecuritypolicy.yaml

/kind bug
> /kind design
Related to https://github.com/falcosecurity/charts/issues/404 and https://github.com/falcosecurity/charts/pull/413
The default grpc socket path recently changed, but this change was not reflected in the PSP to allow the exporter pods to mount the new path. …

fix(falco-exporter): allow new grpc path in falco-exporter PSP

---

README.md
falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/templates/_helpers.tpl
falco/templates/certs-secret.yaml
falco/templates/clusterrolebinding.yaml
falco/templates/configmap.yaml
falco/templates/daemonset.yaml
falco/templates/deployment.yaml
falco/templates/grpc-service.yaml
falco/templates/rules-configmap.yaml
falco/templates/securitycontextconstraints.yaml
falco/templates/serviceaccount.yaml
falco/templates/services.yaml
falco/values.yaml

/kind feature
Allow completely defining falco's deployment using its values.yaml.
Contrasted with the current process, namespace is the only bit of configuration that must be stored somewhere else. Thus deploying requires `helm install falco falcosecurity/falco --values falco/values.yaml --namespace [some-other-source]`. Config being split into two sources adds a layer of complexity, especially in CICD.
Fixes #422
- Testing: Does not break deployments that use the default recommend command `helm install falco falcosecurity/falco --namespace falco`
- I did …

feat: add variable namespaceOverride to falco chart

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/daemonset.yaml
falco/templates/deployment.yaml
falco/values.yaml

/kind feature
It exposes controller's annotations in the `values.yaml` file. This might be useful for some production environments that require specific annotations.
**Checklist**

Expose Falco controller annotations

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/NOTES.txt

/kind bug
It makes part of the NOTES only rendered if `.Values.controller.kind` is set to `daemonset`. It does not make sense to show that part of the notes if the kind os set to `deployment`.
Fixes #448

fix: Only print DaemonSet info if set to DaemonSet

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/deployment-ui.yaml

/kind bug
Adds quotes to number because numbers are not allowed to be used as container arguments.
Fixes #454
**Checklist**

fix(falcosidekick): quote integer redis ttl value

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/secrets.yaml

/kind bug
This pull request fixes an issue in falcosidekick's chart version 0.5.12. The current configuration was using the wrong key in [falcosidekick/templates/secrets.yaml](https://github.com/falcosecurity/charts/blob/9b27a5925f4c8a4d0fd500a2e963d572e2cce767/falcosidekick/templates/secrets.yaml#L176), causing the Prometheus `extralabels` to not be set correctly.
This pull request changes it to:
```yaml
PROMETHEUS_EXTRALABELS: "{{ .Values.config.prometheus.extralabels | b64enc }}"
```
Fixes #451
Coauthored by: @aaniqtejani

fix prometheus extralabels configuration in falcosidekick

---

falco/CHANGELOG.md
falco/Chart.yaml

> /kind bug
/kind cleanup
> /kind design
Bumps falcosidekick dependency to 0.5.14 in the Falco chart.
**Checklist**

Bump falcosidekick dependency to 0.5.14

---

falco/CHANGELOG.md
falco/Chart.yaml

Signed-off-by: Tim Schwenke <tim@trallnag.com>
The pull request https://github.com/falcosecurity/charts/pull/449 introduced an incorrect entry into the changelog.
The entries for v2.4.7 and v2.5.2 are the same, which should not be the case.
https://github.com/falcosecurity/charts/blob/a3a315caec40b145e940ed63d418c59ac8134190/falco/CHANGELOG.md?plain=1#L10-L12
https://github.com/falcosecurity/charts/blob/a3a315caec40b145e940ed63d418c59ac8134190/falco/CHANGELOG.md?plain=1#L24-L26
Related PRs:
- https://github.com/falcosecurity/charts/pull/456
- https://github.com/falcosecurity/charts/pull/449
Happened during a rebase.
Thanks to @bryanasdev000 for noticing this and bringing it up.
Fixes: #461

docs(falco): Fix incorrect entry in changelog

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
The docker image currently used for redis in falcosidekick-ui deployment is deprecated, this PR changes for a maintained image. For users deploying with a PVC, the migration is without data loss. …

Change the docker image for the redis pod for falcosidekick-ui

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/grpc-service.yaml

/kind bug
> /kind design
The provided falco-grpc service app selector does not exist in the pod template.
Adds a label to the the pod template so the service can route traffic to that pod.
Fixes #
There are …

fix: adds app selector to pod template

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/daemonset.yaml
falco-exporter/values.yaml

/kind feature
Add variables for readiness and liveness probes to configure timings such as `initialDelaySeconds`
My first PR, hopefully I have considered everything.
**Checklist**

Add readiness/liveness probe values to falco-exporter-chart

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/values.yaml

/kind bug
The default env key of the init and follow containers expects a map, but the correct value type should be a list.
Fixes #486 
**Checklist**

fix(falco): use list as default for env parameter of init and follow containers

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
falco/generated/helm-values.md
falco/templates/pod-template.tpl
falco/values.yaml

/kind feature
This PR bumps Falco version to Falco 0.35.1. Main changes:
* support modern ebpf in least privileged mode
* bump falcoctl to 0.5.1
**Checklist**

chore: bump chart to Falco 0.35.1

---

.circleci/config.yml
falco/CHANGELOG.md
falco/Chart.yaml
falco/Makefile

> /kind bug
> /kind design
>/area event-generator-chart
The latest version of chart testing adds support for extra args when running helm linting. The timeout flag used for the install command is incompatible with the lint command. We just revert to the prior version until the issue is solved.
See: …

fix(CI): pin chart testing to v3.8.0

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/deployment.yaml
falcosidekick/templates/secrets.yaml
falcosidekick/values.yaml

/kind feature
Update values, env and secrets to fit new features of the next falcosidekick update
None
Ping to @Issif, with the large milestone that v2.28 is, I think that might help a little bit. 
**Checklist**

update(falcosidekick): Upgrade to v2.28

---

event-generator/CHANGELOG.md
event-generator/Chart.yaml
event-generator/templates/deployment.yaml
event-generator/values.yaml
falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/deployment.yaml
falco/values.yaml
falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/deployment-ui.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/values.yaml

/kind feature
I want to clean up old replica sets so that these don't appear in metrics, OPA violations, ArgoCD UI and so on.
Therefore I want to overwrite the Kubernetes default revision history limit.
See [Kubernetes Clean up Policy](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#clean-up-policy).
N/A
**Checklist**

feat: allow changing the default revisionHistoryLimit

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
falco/generated/helm-values.md

> /kind bug
> /kind design
Since Falco 0.36.0 we have a choice of driver loader images. Document this.
Fixes #
**Checklist**

update(docs): add instructions to change driver loader image

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/certs-secret.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/templates/service.yaml
falcosidekick/values.yaml

/kind feature
This PR adds the capability of loading certificates for mTLS communication dynamically via helm values. It's structured in a way to make it easier to deploy mTLS cryptographic material for falcosidekick http server when mTLS is enabled.
N/A
Split of #546.
**Checklist**

Feature: Add mTLS certificate loading for Falco Sidekick via Helm

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/client-certs-secret.yaml
charts/falco/templates/pod-template.tpl
charts/falco/values.yaml

/kind feature
This PR adds the capability of loading certificates for mTLS communication dynamically via Helm values. It's structured in a way to make it easier to deploy mTLS cryptographic material for Falco http_output when mTLS is enabled.
N/A
Substituting #549 
**Checklist**

Feature: Add mTLS certificate loading for Falco via Helm

---

README.md
charts/falco/CHANGELOG.md
charts/falco/Chart.yaml

/kind feature
Upgrade falcosidekick chart to `v0.7.11` in falco chart

Upgrade falcosidekick chart to `v0.7.11` in falco chart

---

.github/workflows/test.yml
charts/k8s-metacollector/CHANGELOG.md
charts/k8s-metacollector/Chart.yaml
charts/k8s-metacollector/values.yaml

> /kind bug
> /kind design
Bump k8s-metacollector version to 0.1.0. Furthermore, enables unit tests for the chart.
Fixes #
**Checklist**

Bump k8s-metacollector version to 0.1.1

---

charts/falco-exporter/CHANGELOG.md
charts/falco-exporter/Chart.yaml
charts/falco-exporter/templates/grafana-dashboard.yaml

/kind feature
Support annotation for grafana
Fixes #
**Checklist**

grafana-dashboard: add support grafana crd

---

charts/k8s-metacollector/CHANGELOG.md
charts/k8s-metacollector/Chart.yaml
charts/k8s-metacollector/README.md
charts/k8s-metacollector/templates/servicemonitor.yaml

/kind bug
> /kind design
fix(k8s-metacollector): correctly indent the service monitor
Fixes #
**Checklist**

fix(k8s-metacollector): correctly indent the service monitor

---

charts/k8s-metacollector/CHANGELOG.md
charts/k8s-metacollector/Chart.yaml
charts/k8s-metacollector/README.md
charts/k8s-metacollector/tests/unit/deploymentTemplate_test.go
charts/k8s-metacollector/values.yaml

> /kind bug
> /kind design
update(k8s-metacollector): lower initial delay of readiness and liveness probes
Fixes #
**Checklist**

update(k8s-metacollector): lower initial delay of readiness and liveness probes

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/templates/pod-template.tpl
charts/falco/templates/serviceaccount.yaml
charts/falco/tests/unit/serviceAccount_test.go
charts/falco/values.yaml

/kind bug
> /kind design
/kind feature
This PR reintroduces the service account removed in the previous release. see #612 
#612 
Fixes #
**Checklist**

fix(falco): reintroduce service account

---

.github/workflows/test.yml
charts/falco-exporter/CHANGELOG.md
charts/falco-exporter/Chart.yaml
charts/falco-exporter/values.yaml
tests/falco-test-ci.yaml

/kind bug
> /kind design
Update the tolerations.
Fixes #
#579 
**Checklist**

fix(exporter): update tolerations

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.gotmpl
charts/falcosidekick/README.md

> /kind bug
> /kind design
Update the README.md file for falcosidekick chart.
Fixes #
**Checklist**

update(falcosidekick): update README.md

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/NOTES.txt

> /kind bug
> /kind design
Fixes links in output after falco install without sidekick
Fixes #
**Checklist**

NOTES.txt: Fix links

---

.github/workflows/docs.yml

> /kind bug
> /kind design
Updates the CI to process all charts when checking for outdated docs.
Fixes #
**Checklist**

update(ci): process all charts for changes in values.yaml

---

charts/falco/BREAKING-CHANGES.md
charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.gotmpl
charts/falco/README.md
charts/falco/values.yaml

> /kind bug
/kind cleanup
> /kind design
This PR fixes typos, formatting, and dead links in falco chart.
Fixes #
**Checklist**

fix typos, formatting, dead links in falco chart

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.gotmpl
charts/falco/README.md

> /kind bug
> /kind design
Fix dead link in docs.
Fixes #
**Checklist**

fix(falco/README.md): dead link

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/_helpers.tpl
charts/falcosidekick/templates/servicemonitor.yaml

/kind bug
fix: mismatch port name in servicemonitor
fix: added component core to selector, overwise prometheus tries to select also falcosidekick-ui (if installed) and fails 
Fixes #
fix: mismatch port name in servicemonitor
fix: added component core to selector, overwise prometheus tries to select also falcosidekick-ui (if installed) and fails 
**Checklist**

Falcosidekick servicemonitor port and selector fix

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/_helpers.tpl

/kind bug
This PR removes the component label `core` from within the _helpers.tpl because it is set specific to each component within the corresponding templates - see https://github.com/falcosecurity/charts/pull/626#issuecomment-1953532813.
*This partly reverts #626.* 
To reproduce this issue run the following on #626:
```
git checkout 70efc03efebf52da11199271af161bf7ab0b656c
helm template falco .  --output-dir /dev/shm/70efc03
kubeconform -strict /dev/shm/70efc03/falcosidekick/templates/rbac.yaml
```
kubeconform will throw the following errors:
```
/dev/shm/70efc03/falcosidekick/templates/rbac.yaml - ServiceAccount …
```

[falcosidekick] fix: remove duplicate component label

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/_helpers.tpl

/kind bug
> /kind design
The way a helper was formatted caused errors with older helm versions. I tested helm `v3.0.0` and it failed to process the falco chart. This PR changes the formatting to fix the issue.
Fixes #635 …

fix(falco/helpers): adjust formatting to be compatible with older helm versions

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/servicemonitor.yaml

/kind bug
Adds component label to ServiceMonitor to scrape falcosidekick containers only and not the UI which produces 404 http responses
Update to #626 where the label was added in the wrong file and produces kubeconform errors #634.
**Checklist**

[falcosidekick] fix: component label in matchers for servicemonitor

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml

/kind bug
Installing falcosidekick through the falco helm chart `falcosidekick.enabled: true` is not using the latest falcosidekick version. The installed version has a bug, which is fixed in this [PR](https://github.com/falcosecurity/charts/pull/626).
[PR](https://github.com/falcosecurity/charts/pull/626)
**Checklist**

bump falcosidekick version in falco chart dependency

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/NOTES.txt

/kind bug
> /kind design
Fix a error in the `NOTES` when `webui.ingress.enabled=true`: `enabled (at <index .paths 0>: error calling index: index of untyped nil Use)`
This has been noticed by an end user who contacted me. …

fix the error with the NOTES when the ingress for falcosidekick-ui is enabled (at <index .paths 0>: error calling index: index of untyped nil Use)

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/pod-template.tpl

> /kind bug
> /kind design
/kind feature
Fixes https://github.com/falcosecurity/deploy-kubernetes/issues/95
/hold for double checking and second opinions
cc @falcosecurity/core-maintainers 
**Checklist**

update(falco): add `HOST_ROOT` and `FALCO_HOSTNAME` by default

---

charts/falco-exporter/CHANGELOG.md
charts/falco-exporter/Chart.yaml
charts/falco-exporter/README.md
charts/falco-exporter/templates/grafana-dashboard.yaml
charts/falco-exporter/values.yaml

/kind feature
This PR adds the ability to set the grafana folder annotation name used by the Grafana sidecar.
This is useful when using [folderAnnotation](https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml#L935) in the Grafana Helm Chart.
Set the default value to the previously hardcoded one.
N/A
**Checklist**

feat(falco-exporter): added ability to set the grafana folder annotation name

---

charts/falco-exporter/CHANGELOG.md
charts/falco-exporter/Chart.yaml
charts/falco-exporter/README.md
charts/falco-exporter/templates/servicemonitor.yaml
charts/falco-exporter/values.yaml

> /kind bug
> /kind design
/kind feature
Fixes #
I've added the capability to the Falco-exporter charts to set additional properties within the Service Monitor, such as relabelings, metricRelabelings, …

8f63167 CHART: add additionalProperties for falco-exporter service Monitor

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/prometheusrule.yaml

/kind bug
Prometheus does not accept duplicate rule name.
The chart Prometheus rules can't be installed as is, leading to an error and preventing the resource to be created.

The sidekick chart Prometheus rules can't be installed as is, leading to an error and preventing the resource to be created.

---

charts/falco-exporter/CHANGELOG.md
charts/falco-exporter/Chart.yaml
charts/falco-exporter/README.md
charts/falco-exporter/templates/grafana-dashboard.yaml

/kind feature
Updated the Falco Grafana dashboard ito make it more user friendly and removed deprecated panels since Grafana 7 (2020).
All details in https://github.com/falcosecurity/charts/issues/656
Fixes #656
**Checklist**

feat: updated grafana dashboard

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/prometheusrule.yaml
charts/falcosidekick/templates/servicemonitor.yaml
charts/falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
Fixes #
I run a helm template, helm lint helm dry-run to test and try the serviceMonitor on Openshift cluster. Test the prometheusRule on grafana. 
**Checklist**

feat : falcosidekick service monitor update add aditionnal properties

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/pod-template.tpl

/kind bug
This PR fixes a check in the falco pod template, which uses the `existingSecret` variable instead of `existingClientSecret` when deciding if client secrets are enabled.
The consequence was that the chart would not work correctly when defining `existingSecret` but not `existingClientSecret`: it would try to attach an unexisting configmap to falco pods
**Checklist**
- [ x ] Chart Version bumped
- [ x ] Variables are documented in the README.md
- [ x ] CHANGELOG.md updated

Fix existing client secret check

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/values.yaml

The default image of redis-stack has been released in February 2023 and is outdated.
This should be updated to a more recent tag (see https://hub.docker.com/r/redis/redis-stack/tags).
-/-
**Checklist**

chore(falcosidekick): upgrade redis-stack image to 7.2.0-v11

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/daemonset.yaml
charts/falco/templates/deployment.yaml
charts/falco/values.yaml

/kind feature
This PR adds an extra field: `controller.labels` which allows users to set extra labels for the Falco daemonset/deployment.

Feat: add extra labeling capabilities for falco daemonset/deployment

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/pod-template.tpl

/kind bug
Fixes #632 
to allow falco to reconnect if containerd got restarted on host
**Checklist**

use directory-mapping instead of simple containerd.socket-file-mapping

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/_helpers.tpl
charts/falco/templates/configmap.yaml
charts/falco/templates/service.yaml
charts/falco/templates/serviceMonitor.yaml
charts/falco/tests/unit/metricsConfig_test.go
charts/falco/tests/unit/serviceMonitorTemplate_test.go
charts/falco/values.yaml

> /kind bug
> /kind design
/kind feature
This PR adds support for Falco metrics in the Falco chart.
Fixes #
**Checklist**

feat(falco): add support for Falco metrics

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/deployment-ui.yaml
charts/falcosidekick/values.yaml

/kind feature
If someone wants to define resource limits or a security context for the wait-redis init container, this change can be useful.
The default values are empty and therefore this change won't break any existing setup.
It also allows the user to update or replace the busybox image.
Setting resource limits and security contexts are forced in many organizations, e.g. by using checkov and gatekeeper policies.
n/a
**Checklist**

feat(falcosidekick): allow to set resources, securityContext and image overwrite for wait-redis initContainer

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/deployment-ui.yaml

/kind bug
It fixes the redis-availability check of the UI init-container in case external-redis is enabled. It was using the hard-coded value used when you would not use an exernal-redis.
I also upgraded the chart-version of the sidekick and flaco to get the fix also into the falco chart. It would certainly support the use I have - but I don't know if bumping two versions at once is something you do. Let me know.

Fix redis-availability check in UI

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml

Updates the sidekick dependency on falco so that the fix of redis-external is included.

Bump falco-sidekick dependency version to include redis UI check

---

charts/k8s-metacollector/CHANGELOG.md
charts/k8s-metacollector/Chart.yaml
charts/k8s-metacollector/README.md
charts/k8s-metacollector/templates/deployment.yaml
charts/k8s-metacollector/values.yaml

/kind feature
Adding podLabels for the k8s-metacollector chart

chore(k8s-metacollector): Add podLabels

---

charts/falco-exporter/CHANGELOG.md
charts/falco-exporter/Chart.yaml
charts/falco-exporter/README.md
charts/falco-exporter/templates/prometheusrule.yaml
charts/falco-exporter/values.yaml

/kind feature
This PR makes the `for` field configurable within the helm values. 
N/a

Make 'for' configurable for falco exporter prometheus rules

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/tests/unit/k8smetacollectorDependency_test.go
charts/falco/values.yaml

/kind bug
> /kind design
The new version resolves a bug that prevented the k8smeta fields from being populated for pods deployed before Falco.
Fixes #
https://github.com/falcosecurity/plugins/issues/514
**Special notes for …

update(k8smeta): bump k8smeta version to 0.2.0

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/service-ui.yaml

/kind bug
This PR fixes an issue in the Helm chart where the WebUI Redis service type was hardcoded to `ClusterIP`, ignoring the user-configured value under `webui.redis.service.type`.
**Checklist**

fix(falcosidekick): add support for custom service type for webui redis in Helm chart

---

charts/event-generator/CHANGELOG.md
charts/event-generator/Chart.yaml
charts/event-generator/README.md
charts/event-generator/templates/pod-template.tpl

/kind bug
Currently users who follow the [example config given here](https://github.com/falcosecurity/charts/blob/ba95f4cbf29a66727535c9460aa8b4f6a778b1f1/charts/event-generator/README.md?plain=1#L85) will see event-generator fail to start.
That's because the rules that match that regexp will only run when the `--all` [flag is provided](https://github.com/falcosecurity/event-generator/blob/7b0dab5d35e270084e84f2ba2156ae385feea3b6/docs/event-generator_run.md?plain=1#L25) because they are [marked as disabled](https://github.com/falcosecurity/event-generator/blob/main/events/k8saudit/yaml_disabled.go).
* …

Fix running of k8saudit actions

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/pod-template.tpl

/kind bug
> /kind design
When falco runs with kmod/module driver it needs special filesystems to be mounted from the host such /dev and /sys/module/falco. This commit ensures that we mount them in the falco container.
Note that, the /sys/module/falco is now …

fix(falco): correctly mount host filesystems when driver.kind is auto

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/configmap-ui.yaml
charts/falcosidekick/templates/deployment-ui.yaml
charts/falcosidekick/templates/prometheusrule.yaml
charts/falcosidekick/templates/secrets-ui.yaml
charts/falcosidekick/templates/secrets.yaml
charts/falcosidekick/templates/service-ui.yaml
charts/falcosidekick/values.yaml

/kind bug
> /kind design
/kind feature
- Use of `redis-cli` by the initContainer of Falcosidekick-UI to wait til the redis is up and running
- Add the possibility to override the default redis server settings
- Allow to set up a password to use with an external redis …

use redis-cli for the initContainer check

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/configmap-ui.yaml

/kind bug
Currently defining `falcosidekick.webui.redis.customConfig`in `values.yaml` results in templating error:
```
Error: YAML parse error on falco/charts/falco/charts/falcosidekick/templates/configmap-ui.yaml: error converting YAML to JSON: yaml: line 17: 
did not find expected key
```
Using `--debug` switch shows us that one line is unnecessary suppressed (the key `data` is joined with `redis-stack.config`):
```yaml
data:redis-stack.config: |-
maxmemory-policy allkeys-lfu
maxmemory 4096mb
``` 
Tested with `values.yaml`:
```yaml
falcosidekick:
webui:
redis:
customConfig: 
- maxmemory-policy allkeys-lfu
- maxmemory …
```

fix(falcosidekick): customConfig template fix for webui redis

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/service.yaml
charts/falco/tests/unit/chartInfo.go
charts/falco/tests/unit/serviceTemplate_test.go
charts/falco/values.yaml

I want to add the possibilty to put annotations on the metrics service to be scraped by my OTEL collector
> /kind design
We need it to scrape the metrics with an external service monitor
Fixes #
**Checklist**

Add possibility to add annotations to the metrics service

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/configmap-ui.yaml
charts/falcosidekick/templates/deployment-ui.yaml

/kind bug
redis-stack expects [configuration in file /redis-stack.conf](https://github.com/redis-stack/redis-stack/blob/9948f22324e7a89569a83c20d023cb91d0a92c3a/etc/scripts/entrypoint.sh#L9):
```bash
if [ -f /redis-stack.conf ]; then
CONFFILE=/redis-stack.conf
fi
```
However currently the ConfigMap/StatefulSet templates mount the configuration over at `/redis-stack.config`, so it doesn't get applied despite defining `customConfig` in values [[1](https://github.com/falcosecurity/charts/blob/9483726553d9d2a3b46c0fc27764b5c1161433ae/charts/falcosidekick/templates/configmap-ui.yaml#L13)] …

fix(falcosidekick): customConfig mount path fix for webui redis

---

.github/PULL_REQUEST_TEMPLATE.md
charts/falco-talon/CHANGELOG.md
charts/falco-talon/Chart.yaml
charts/falco-talon/README.gotmpl
charts/falco-talon/README.md
charts/falco-talon/rules.yaml
charts/falco-talon/rules_override.yaml
charts/falco-talon/templates/_helpers.tpl
charts/falco-talon/templates/clusterrole.yaml
charts/falco-talon/templates/configmap.yaml
charts/falco-talon/templates/deployment.yaml
charts/falco-talon/templates/ingress.yaml
charts/falco-talon/templates/podsecuritypolicy.yaml
charts/falco-talon/templates/rbac.yaml
charts/falco-talon/templates/secrets.yaml
charts/falco-talon/templates/servicemonitor.yaml
charts/falco-talon/templates/services.yaml
charts/falco-talon/values.yaml

/area falco-talon
Fixes #
**Checklist**

add falco-talon chart

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/dashboards/falco-dashboard.json
charts/falco/templates/falco-dashboard-grafana.yaml
charts/falco/tests/unit/grafanaDashboards_test.go
charts/falco/values.yaml

> /kind bug
> /kind design
/kind feature
This PR adds a default grafana dashboard for falco. The following snipped shows how it can be enabled and configured:
```bash
helm install falco falcosecurity/falco \
--namespace falco \
--create-namespace \
--set …
```

new(falco): add grafana dashboard for falco

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/_helpers.tpl

> /kind bug
/kind cleanup
> /kind design
Outputting the env key without values is highlighted as error in vscode.
Fixes #
**Checklist**

fix: only prints env key if there are env values to be passed.

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/_helpers.tpl
charts/falco/tests/unit/k8smetacollectorDependency_test.go
charts/falco/values.yaml

> /kind bug
> /kind design
/kind feature
new(falco/collectors): expose new config options for k8smeta pluginsKcl/add k8smeta config options
Fixes #
**Checklist**

new(falco/collectors): expose new config options for k8smeta

---

charts/falco-talon/CHANGELOG.md
charts/falco-talon/Chart.yaml
charts/falco-talon/templates/configmap.yaml

/kind bug
> /kind design
/area falco-talon
attempt to fix an issue with a range to collect rules files content
Fixes #
**Checklist**

change the key for the rulesfiles range

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/tests/unit/k8smetacollectorDependency_test.go
charts/falco/values.yaml

/kind bug
> /kind design
Fixes #
**Checklist**

bump k8smeta plugin

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/dashboards/falco-dashboard.json

/kind bug
> /kind design
fix(falco/dashboard): make pod variable independent of triggered rules
CPU and memory are now visible for each pod, even when no rules have been triggered for
that falco instance.
**Which issue(s) this PR …

fix falco dashboard variable

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

Current snippet in chars/falco/README.md that uses `rules_file` causes collision with `rules_files` and falco does not start
```
Tue Nov 12 14:23:17 2024: Using deprecated config key 'rules_file' (singular form). Please use new 'rules_files' config key (plural form).
Error: Error reading config file (/etc/falco/falco.yaml): both 'rules_files' and 'rules_file' keys set
```

fix: Use rules_files instead of deprecated rules_file in README.md config snippet

---

.lycheeignore
charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/secrets.yaml
charts/falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
Upgrade Falcosidekick to 2.30.0
Fixes #
**Checklist**

upgrade to falcosidekick 2.30.0

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/pod-template.tpl

/kind bug
This PR modify the helm chart for Falco to set the `dnsPolicy` of the falco pod to `ClusterFirstWithHostNet` when the gVisor driver is enabled.
This is needed because right now, the dnsPolicy falls back to the `Default` mode of Kubernetes (see https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy) as the falco pod runs with `hostNetwork` set to true when gVisor is enabled https://github.com/falcosecurity/charts/blob/15f97d55f6c2ddbeb6fefbbb4e8f663d835005af/charts/falco/templates/pod-template.tpl#L60-L63
This is an issue as this `Default` mode uses the node DNS servers, and not the Kubernetes cluster …

fix(falco): set dnsPolicy to ClusterFirstWithHostNet when gvisor driver is enabled

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/dashboards/falcosidekick-loki-dashboard.json
charts/falcosidekick/templates/falcosidekick-loki-dashboard-grafana.yaml
charts/falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
Fixes #
**Checklist**

feat: added dahsboard and template

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/dashboards/falcosidekick-grafana-dashboard.json
charts/falcosidekick/templates/configmap-grafana-dashboard.yaml
charts/falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
Allow to create a configmap for a Grafana dashboard for the Prometheus metrics of Falcosidekick
Fixes #
I followed the same pattern than …

add a grafana dashboard for the falcosidekick metrics

---

charts/falco-talon/CHANGELOG.md
charts/falco-talon/Chart.yaml
charts/falco-talon/README.md
charts/falco-talon/dashboards/falco-talon-grafana-dashboard.json
charts/falco-talon/templates/configmap-grafana-dashboard.yaml
charts/falco-talon/templates/configmap.yaml
charts/falco-talon/values.yaml

> /kind bug
> /kind design
/kind feature
/area falco-talon
Add a Grafana dashboard for the Prom metrics for Talon
Fixes #
**Checklist**

add a grafana dashboard for the falco talon metrics

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/prometheusrule.yaml

/kind bug
> /kind design
It is a follow-up of https://github.com/falcosecurity/falcosidekick/pull/995
Fixes #
I've already fixed the corresponding labels …

Fix metrics nomenclature

---

.github/dependabot.yml

/kind cleanup
- remove non existing labels
Fixes #
**Checklist**

remove non existing labels

---

.github/workflows/release.yml
cr.yaml

> /kind bug
> /kind design
Enables release note generation via an [option](https://github.com/helm/chart-releaser#create-github-releases-from-helm-chart-packages) provided by chart-releaser. chart-releaser uses GitHub's feature for …

chore(github): Generate release notes

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/service.yaml
charts/falcosidekick/values.yaml

/kind bug
We are working on a migration from a deprecated Prometheus setup to one based on the Prometheus Kubernetes Operator.
Since metrics scraped by the operator-managed instances are targeting ServiceMonitor and PodMonitor resources, we need to be able to configure the `prometheus.io/scrape` Service annotation to gradually disable scraping from our deprecated instances.
Because the `prometheus.io/scrape` annotation is hard-coded in the Service template **and** it's the last entry in the `annotations` map, there's no way to include custom values after it.
This PR simply moves the …

fix(falcosidekick): Allow overriding the Prometheus scrape Service annotation

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/pod-template.tpl

/kind bug
This PR adds a ports: section to the Falco container when the webserver/metrics settings are enabled. Without this change, the port isn’t properly exposed, preventing tools like Prometheus or Grafana from scraping metrics. By exposing the webserver port in the Pod spec, other services can now access it as intended.
Fixes #812
No special notes. I’ve already updated the corresponding labels on GitHub.
**Checklist**

Add ports definition for webserver

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/deployment.yaml
charts/falcosidekick/templates/rbac.yaml
charts/falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
Currently, Falcosidekick supports only Azure Pod Identity. However, the modern and Microsoft-recommended approach is to use Workload Identity.
Fixes #
**Special …

feat(helm): add Azure Workload Identity support for Falcosidekick

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/dashboards/falcosidekick-loki-dashboard.json

New update on the falcosidekick dashboard for loki, added some filtering options. Working with this dashboard I notice this filtering options are a must to have.
> /kind bug
> /kind design
/kind feature
Added filtering options (priority and …

Feat falcosidekick dashboard v2

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/serviceaccount.yaml
charts/falco/values.yaml

> /kind bug
> /kind design
/kind feature
kind chart-release
For most use cases, it is recommended to specify imagePullSecrets at the ServiceAccount level if all pods using that ServiceAccount need access to the same image pull secrets. This approach simplifies …

new(falco): adding imagePullSecrets at the service account level
