OWNERS

Needed before enabling @poiana 🐦

update: adding leogr, nibalizer (approvers + reviewers), nestorsalceda & bencer (as reviewers only)

---

falco/Chart.yaml

update(falco): update maintainers in Chart.yaml

---

OWNERS

new: OWNERS

---

falco/README.md

Co-Authored-By: Leonardo Grasso <me@leonardograsso.com>
Signed-Off-By: Lorenzo Fontana <lo@linux.com>

docs: remove dead link to old Falco profiles

---

falco/README.md

Helm3 style commands and minor fixes.

docs(falco): adjust examples for helm 3

---

falco/README.md

/cc @fntlnz 
/cc @kris-nova 
/cc @leodido

docs(falco): auditLog

---

.circleci/config.yml

Signed-off-by: xantrix <x4ntrix@gmail.com>
/kind feature
Related to #31 
Skipping any CircleCI activity on gh-pages branch
/cc @leogr

Skipping any CircleCI activity on gh-pages

---

falco/Chart.yaml

fix(falco): correct wrong version number

---

.circleci/config.yml
.circleci/lint.sh

Fixes #45 
/cc @fntlnz 
/cc @leodido 
/cc @nibalizer

build(.circleci): charts linting

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
release.md

/cc @nibalizer 
/cc @leodido 
/cc @fntlnz 
Please feel free to suggest any modification/improvement!

releasing process documentation and related stuff

---

falco/README.md
falco/templates/_helpers.tpl
falco/templates/configmap.yaml
falco/templates/daemonset.yaml
falco/templates/secret-certs.yaml
falco/templates/service.yaml
falco/values.yaml

/kind feature
Fixes #27 
To be kept on hold until Falco 0.24.0
/hold
TODOs:
/cc @leodido
/cc @fntlnz

grpc unix socket

---

.github/PULL_REQUEST_TEMPLATE.md
README.md
falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/NOTES.txt
falco-exporter/templates/_helpers.tpl
falco-exporter/templates/daemonset.yaml
falco-exporter/templates/secret-certs.yaml
falco-exporter/templates/service.yaml
falco-exporter/templates/serviceaccount.yaml
falco-exporter/templates/tests/test-connection.yaml
falco-exporter/values.yaml

/kind feature
This PR moves [falco-exporter chart sources](https://github.com/falcosecurity/falco-exporter/tree/master/deploy/helm/falco-exporter) here, as discussed in #47
Fixes #
**Checklist**

move falco-exporter chart here

---

falco-exporter/README.md

Just small typo in the README.
Fixes #
**Checklist**

docs(falco-exporter): correct default value for image version

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/servicemonitor.yaml

/kind bug
Fixes #64
**Checklist**

fix(falco-exporter): correct additional labels for servicemonitor

---

README.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/NOTES.txt
falcosidekick/templates/_helpers.tpl
falcosidekick/templates/aadpodidentity.yaml
falcosidekick/templates/clusterrole.yaml
falcosidekick/templates/clusterrolebinding.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/templates/ingress.yaml
falcosidekick/templates/rbac.yaml
falcosidekick/templates/secrets.yaml
falcosidekick/templates/service.yaml
falcosidekick/templates/tests/test-connection.yaml
falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
Add `falcosidekick` chart
N/A
Fixes #
**Checklist**

add falcosidekick chart

---

falcosidekick/Chart.yaml

/kind bug
> /kind design
The previous PR wasn't successful, an error with linting in `Chart.yaml` crashed the CI before to release.
N/A
Fixes #
**Checklist**

Fix falcosidekick chart linting

---

.github/PULL_REQUEST_TEMPLATE.md

Since we have falcosidekick, we also need a label for it :)
Fixes #
cc @Issif

docs(.github): add `area/falcosidekick`

---

falcosidekick/Chart.yaml
falcosidekick/templates/aadpodidentity.yaml

From Azure pod identity 1.6.0 en onward CRD fields are case sensitive and must be camelcase.
Fixes #
**Checklist**

[falcosidekick] From Azure identity >=1.6.0 CRD on fields are case sensitive

---

falcosidekick/Chart.yaml
falcosidekick/templates/deployment.yaml

/kind bug
> /kind design
Fixes typo in deployment template, so you can successfully add a slack webhook url without it also requiring a discord webhook url. 
Fixes #
**Checklist**

Fix falcosidekick chart typo

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/grafana-dashboard.yaml
falco-exporter/values.yaml

Signed-off-by: daan <daan.potter@nn-group.com>
> /kind bug
> /kind design
/kind feature
Insert grafana dashboard into helm chart
Fixes #
**Checklist**

Add grafana dashboard

---

falcosidekick/Chart.yaml

This PR just follows up the already-merged #84 since the release process did not initiate.
Basically, the #84 set the same version already present on the master branch (that did not conflict because of the GitHub rebase).
Fixes #
**Checklist**

release(falcosidekick): 0.1.23

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml

> /kind bug
> /kind design
This PR adds a Change log for `falcosidekic` helm chart and use better avatar for helm hub.
Fixes #79
**Checklist**

add Changelog for falcosidekick helm chart

---

OWNERS

> /kind bug
/kind cleanup
> /kind design
Add me (@Issif) as owner/reviewer, as main developper of `falcosidekick`, I need to be able to approve PR for.
N/A
N/A
**Checklist**

add Issif as owner/reviewer

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/values.yaml

Signed-off-by: thomas.labarussias <thomas.labarussias@qonto.eu>
> /kind bug
> /kind design
A duplicated block for `webhook` is in values.yaml
Fixes #88 
**Checklist**

remove duplicated webhook block in values.yaml

---

falco/README.md

Fix broken link to k8s_audit_config

---

falco-exporter/README.md

Hi @leogr,
Here the fixed copy & paste error with dco. Hope it's fine like this now 😄?
Regards,
Philip

Fixed copy & paste error

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/ci/ebpf-values.yaml
falco/rules/falco_rules.yaml
falco/rules/k8s_audit_rules.yaml
falco/templates/_helpers.tpl
falco/templates/clusterrole.yaml
falco/templates/clusterrolebinding.yaml
falco/values.yaml

/kind feature
Fixes #104
/hold
until Falco 0.26.1 gets released
/cc @leodido 
/cc @fntlnz 
**Checklist**

release(falco): v1.5.0 upgrades Falco to 0.26.1

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/daemonset.yaml
falco-exporter/values.yaml

> /kind bug
> /kind design
/kind feature
Fixes #
**Checklist**

Add priorityClassName to falco-exporter values

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/podsecuritypolicy.yaml

Fixes #110
/kind bug
**Checklist**

Add PodSecurityPolicy for falcosidekick

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/podsecuritypolicy.yaml

/kind bug
**What this PR does / why we need it**: See linked issue.
Fixes https://github.com/falcosecurity/charts/issues/115
**Special notes for your reviewer**: I also bumped chart version from `0.3.5` to `0.3.6`. @leogr: Sorry for introducing this bug :hankey:.
**Checklist**

Added secret volume type to PSP

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
falco/templates/NOTES.txt

> /kind bug
/kind cleanup
> /kind design
/kind feature
This PR introduces a deprecation notice for those integrations that will be removed soon, as discussed in #123, and during our community calls.
It also cleans up the documentation and removes some old references.
Fixes #
/cc …

Falco deprecation notice for integrations

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/values.yaml

> /kind bug
> /kind design
Fixes #
/cc @fntlnz 
/cc @leodido  
**Checklist**

release(falco): 1.5.4

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/NOTES.txt
falco-exporter/templates/daemonset.yaml
falco-exporter/templates/server-secret-certs.yaml
falco-exporter/values.yaml

Signed-off-by: Jose Angel Santiago <>
/kind feature
It allows to deploy falco-exporter with Mutual TLS feature enabled
**Checklist**

new: Add Mutual TLS deployment

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/aadpodidentity.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/templates/ingress.yaml
falcosidekick/templates/rbac.yaml
falcosidekick/templates/secrets.yaml
falcosidekick/templates/service.yaml
falcosidekick/templates/tests/test-connection.yaml

Signed-off-by: KeisukeYamashita <19yamashita15@gmail.com>
> /kind bug
> /kind design
/kind feature
Supported `namespace` for namespace-specific resources.
This also helps this chart to support `helm template` (Solves: https://github.com/falcosecurity/charts/issues/122 for Falco Sidekick)
Fixes # …

Support release namespace

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/grafana-dashboard.yaml
falco-exporter/templates/role.yaml
falco-exporter/templates/rolebinding.yaml
falco-exporter/templates/secret-certs.yaml
falco-exporter/templates/securitycontextconstraints.yaml
falco-exporter/templates/server-secret-certs.yaml
falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/auditsink.yaml
falco/templates/configmap-rules.yaml
falco/templates/configmap.yaml
falco/templates/daemonset.yaml
falco/templates/deployment.yaml
falco/templates/secret-certs.yaml
falco/templates/secret.yaml
falco/templates/securitycontextconstraints.yaml
falco/templates/service.yaml
falco/templates/serviceaccount.yaml

> /kind bug
> /kind design
/kind feature
Add `{{ .Release.Namespace }}` to support `helm template`. 
Solves [Add support to chart to work with 'helm template'](https://github.com/falcosecurity/charts/issues/122)
Fixes #122
**Checklist**

Support release namespace for falco-exporter and falco

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/deployment.yaml

> /kind bug
/kind cleanup
> /kind design
This PR updates the Falco Sidekick Helm template's values to grab the correct values from `values.yaml` for the GCP Pub/Sub Integration.
Fixes #
**Checklist**

updated deployment template with correct path to values GCP config values

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/clusterrole.yaml
falcosidekick/templates/clusterrolebinding.yaml
falcosidekick/templates/rbac.yaml
falcosidekick/values.yaml

/kind feature
falcosidekick: update image to use release 2.19.1
Fixes #
**Checklist**

falcosidekick: update image to use release 2.19.1

---

falcosidekick/templates/deployment.yaml
falcosidekick/values.yaml

Signed-off-by: DingGGu <ggu@dunamu.com>
/kind bug
> /kind design
Fixes #
**Checklist**

Add missing configuration checkcert

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/tests/test-connection.yaml

/kind bug
the helm test was failing for falcosidekick because it does not accept a GET method only a POST
This PR fixes that and use the `/ping` endpoint to test the connection
Fixes #
**Checklist**

fix helm test for falcosidekick

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/values.yaml

/kind bug
falcosidekick: fix aws keys not being added to the deployment
Fixes #
**Checklist**

falcosidekick: fix aws keys not being added to the deployment

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
falco/templates/auditsink.yaml
falco/templates/configmap.yaml
falco/templates/daemonset.yaml
falco/templates/secret-certs.yaml
falco/values.yaml

/kind bug
/kind feature
- Add `falco.webserver.sslEnabled` config, enabling SSL support using the `certs` values from gRPC
- Document `certs` values
Fixes #38
Testing SSL support might require a docker image with libssl1.0 installed if it's not statically linked yet
For SSL, the certificate has to be valid for the loopback IP used in the API server config.
**Checklist**

falco: k8s-audit: Add SSL support

---

.github/PULL_REQUEST_TEMPLATE.md

> /kind bug
> /kind design
Fixes #
**Checklist**

docs(.github): correct area label for falcosidekick-chart

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/secrets.yaml
falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
Falcosidekick now supports PagerDuty output.
Fixes #
**Checklist**

Add PagerDuty configuration to falcosidekick

---

OWNERS

Per invite from the Falco community and existing maintainers, adding @cpanato to the owner file for the Falco Charts repository
Fixes #
**Checklist**

owners: add cpanato as reviewer

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/values.yaml

> /kind bug
> /kind design
/kind feature
Fixes #
**Checklist**

release(falco-exporter): v0.5.0

---

tests/ct.yaml

/kind cleanup
the `helm-extra-args` settings accept any helm flags, the `timeout` flag uses only an integer and we set that as a seconds, dont need to set the `s`. 
Fixes #
**Checklist**

ci: fix helm extra args parameter

---

falco/.gitignore
falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/configmap.yaml
tests/ct.yaml

/kind bug
> /kind design
When `falcosidekick` is enabled, its service is not correctly set for `httpOutput` of `falco`
https://github.com/falcosecurity/falcosidekick/issues/178
Fixes # …

fix service to use as httpOutput when falcosidekick is enabled

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/secrets.yaml
falcosidekick/values.yaml

/kind bug
> /kind design
Adds the value for `config.datadog.host` to the secret created by the chart. If this is not done the value will have no effect on falcosidekick.
**Checklist**

Add DATADOG_HOST to secret

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/values.yaml

/kind bug
> /kind design
This PR fixes an wrong ref for repo of `falcosidekick-ui`
Fixes #
**Checklist**

fix image repo for ui

---

falco/CHANGELOG.md
falco/Chart.yaml

> /kind bug
> /kind design
We used a wilcard for specifying the version of dependency for `falcosidekick` chart. It appears the version is set hardly before push on helm repo. It means the version is stucked until next release of `falco` chart. It's not the behavior we …

use last version of falcosidekick chart

---

falco/Chart.yaml
falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/aadpodidentity.yaml

fix aad pod identity

---

falco/CHANGELOG.md
falco/Chart.yaml

Signed-off-by: daan <dhapotter@gmail.com>
For https://github.com/falcosecurity/charts/pull/189

update downstream chart

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md

Fixes #92
Fixes #147
**Checklist**

docs(falco): init container

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/values.yaml

Signed-off-by: fjogeleit frank.jogeleit@web.de
> /kind bug
> /kind design
Update falcosidekick-ui image version to v0.2.0
Fixes #
**Checklist**

[falcosidekick-ui] Update image version to v0.2.0

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md

> /kind bug
> /kind design
Fixes #
**Checklist**

docs(falco): clarification about the driver

---

falco/CHANGELOG.md
falco/Chart.yaml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
> /kind bug
> /kind design
Fixes #
**Checklist**

falcosidekick version is upgraded on the dependencies side of Falco chart and Falco chart version is also bumped to v1.8.0

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/rules/falco_rules.yaml
falco/rules/k8s_audit_rules.yaml
falco/values.yaml

> /kind bug
> /kind design
/kind feature
Fixes #
**Checklist**

upgrade Falco to 0.28.0

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/values.yaml

> /kind bug
> /kind design
Use last version of `falcosidekick-ui` image (`v1.0.1`)
Fixes #
**Checklist**

Bump up version (v1.0.1) of image for falcosidekick-ui

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md

Signed-off-by: Leonardo Di Donato <leodidonato@gmail.com>
/kind cleanup
Fixes a wrong link in the README
NONE
**Checklist**

docs(falcosidekick): fix link to Falco in the README

---

falco/CHANGELOG.md
falco/Chart.yaml

> /kind bug
> /kind design
Use last version of `falcosidekick` chart for deploying `v1.0.1` of `falcosidekick-ui`
Fixes #
**Checklist**

[falco] update falcosidekick chart to v1.10.0

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/aadpodidentity.yaml

Signed-off-by: Edvin Norling <edvin.norling@xenit.se>
/kind bug
> /kind design
aadpodidentity not pointing to correct name in pod definition.
N/A
Fixes #
**Checklist**

Set correct aadpodidentity name

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/values.yaml

misspell fullfqdn

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/values.yaml

/kind bug
Fixes #
**Checklist**

fix(falco): update image tag to 0.29.0

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/deployment-ui.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/templates/secrets.yaml
falcosidekick/values.yaml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
This PR will add GCP Cloud Functions and GCP Cloud Run outputs support to Falcosidekick
Fixes #
**Checklist**

updates for falcosidekick 0.23.1

---

falco/CHANGELOG.md
falco/Chart.yaml

> /kind bug
> /kind design
This PR update version of chart for `falcosidekick` used as dependency
Fixes #
**Checklist**

prepare falco chart for 1.15.0

---

falco/CHANGELOG.md
falco/Chart.yaml

Signed-off-by: Kaizhe Huang <khuang@aurora.tech>
> /kind bug
> /kind design
Falcosidekick version has been updated in #261 
Fixes #
**Checklist**

bump falcosidekick dependency version

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/deployment.yaml
falcosidekick/values.yaml

/kind feature
This PR adds support for extra volumes in falco UI deployment. An example connect mtls certificates from secret to specific path so that one can use MTLS in outputs.
Fixes #
**Checklist**

Added support for extra volumes for falcosidekick

---

falco/CHANGELOG.md
falco/Chart.yaml

Signed-off-by: Jakub Vavřík <jakub.vavrik@ysoft.com>
> /kind bug
> /kind design
Bumps version of falcosidekick to include extraVOlumes feature from https://github.com/falcosecurity/charts/pull/260
Fixes #
**Checklist**

bumped version of falcosidekick

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/values.yaml

/kind bug
> /kind design
removes an invalid suggestion of setting maxSurge in a daemonset pod on line 77 of values.yaml
Fixes #
**Checklist**

removed maxSurge reference from values.yaml

---

README.md

This PR adds specific contributing instructions for this repository. I believe that can be of particular help for first-time contributors.
A significant example of questions asked by contributors can be found in [this comment](https://github.com/falcosecurity/charts/pull/264#issuecomment-889343269).
Fixes #
**Checklist**

docs(README.md): add `contributing` section

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/secrets.yaml
falcosidekick/values.yaml

/kind feature
Fixes #
**Checklist**

prepare v2.24.0 for falcosidekick

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/values.yaml

Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>
/kind bug
Fixes #
**Checklist**

falcosidekick version bumped to 2.24.0

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/values.yaml

Upgrade falco-exporter to v0.6.0

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/service.yaml
falcosidekick/values.yaml

Reopen from https://github.com/falcosecurity/charts/pull/281 and https://github.com/falcosecurity/charts/pull/282
/kind feature
In some cases, it is required to specify annotations for the service.
Service and ingress variables are not described in README.md
**Checklist**

Support annotation block in service

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/daemonset.yaml
falco-exporter/values.yaml

/kind feature
Update PR based on https://github.com/falcosecurity/charts/pull/203
Fixes #
**Checklist**

Add falco-exporter daemonset annontations

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/servicemonitor.yaml

> /kind bug
> /kind design
/kind feature
To avoid getting an error when deploying the falco-exporter with a helm chart when there is no prometheus operator in your k8s cluster.
Fixes #
**Checklist**

[falco-security] Check availability of 'monitoring.coreos.com/v1' api version

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/serviceaccount.yaml
falco/values.yaml

> /kind bug
> /kind design
/kind feature
This PR is based on #268 which is valuable but unfortunately, the original author is not replying. 
Basically, I have rebased the #268 branch and added the missing commits here.
Fixes #
**Checklist**

Add Service Account annotations

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/prometheusrule.yaml
falco-exporter/values.yaml

- feat(falco-exporter): add prometheusRules option
- chore(Chart.yaml): bump version
/kind feature
Adds custom prometheusRules to alert on different priority events (by looking at the rate)
n/a
n/a
**Checklist**

feat/falco exporter/add prometheusrules

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/daemonset.yaml
falco-exporter/values.yaml

Signed-off-by: Chelo Montilla <chelo.montilla@lansweeper.com>
> /kind bug
> /kind design
/kind feature
Add customized labels to daemon set labels (falco-exporter) 
Fixes #
**Checklist**

Feat/falco exporter/add podlabels

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/values.yaml

Signed-off-by: kirin-13 <kirin_13@163.com>
> /kind bug
> /kind design
Fixes #
**Checklist**

fix: priority level "info" to "informational"

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/service-ui.yaml
falcosidekick/values.yaml

Signed-off-by: igoritos22 <igoritos_22@hotmail.com>
> /kind bug
> /kind design
/kind feature
Allow add annotations to falcosidekick-ui service 
Fixes #
**Checklist**

Allow additional service-ui annotations

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/daemonset.yaml

/kind bug
> /kind design
Follow-up of https://github.com/falcosecurity/charts/pull/324 (which unfortunately did not fix the issue).
Fixes #
**Checklist**

further fix for reuse values with crio2

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/rules/k8s_audit_rules.yaml

/kind bug
> /kind design
Fixes https://github.com/falcosecurity/charts/issues/318 - missing comma in the `allowed_kube_namespace_image_list` list
Fixes https://github.com/falcosecurity/charts/issues/318
**Checklist**

fix missing comma for issue 318

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/NOTES.txt

/kind bug
> /kind design
The url on NOTES.txt was wrong, it returns a 404.
This PR fixes it, now it's pointing to the right place on master branch.
Fixes 332
**Checklist**

Fix Falcosidekick char url on NOTES.txt

---

falco/CHANGELOG.md
falco/Chart.yaml

> /kind bug
> /kind design
/kind feature
update dependency Falcosidekick for Falco chart
Fixes #
**Checklist**

update dependency Falcosidekick for Falco chart

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/values.yaml

…n ingress is used)
/kind bug
> /kind design
https://github.com/falcosecurity/falcosidekick-ui/issues/50
Fixes #
**Checklist**

Update Falcosidekick-UI image

---

falco/CHANGELOG.md
falco/Chart.yaml

> /kind bug
> /kind design
/kind feature
This PR updates the dependency of Falcosidekick chart, which brings a fix for the ingress for the UI
Fixes #
**Checklist**

Update Falcosidekick chart dependency to 0.5.2

---

falco/CHANGELOG.md
falco/Chart.yaml

Co-authored-by: toversus <toversus2357@gmail.com>
> /kind bug
> /kind design
Fixes #
**Checklist**

docs(falco): remove leftover in the changelog

---

falco/CHANGELOG.md
falco/Chart.yaml

> /kind bug
> /kind design
/kind feature
Update Falcosidekick chart dependency to 0.5.4
Fixes #
**Checklist**

Update Falcosidekick chart dependency to 0.5.4

---

README.md

> /kind bug
> /kind design
Update the README.md file by adding the `event-generator` reference to the available charts.
Fixes #
**Checklist**

update(docs): add event-generator to the charts list

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/pod-template.tpl

```
Co-authored-by: Ahmed Amin <run_2005_2005@yahoo.com>
```
/kind bug
> /kind design
This PR fixes templating for init containers in pod-template.tpl file.
Fixes # …

fix(falco): fix templating for init containers in pod-template.tpl

---

event-generator/CHANGELOG.md
event-generator/Chart.yaml
event-generator/templates/pod-template.tpl

/kind bug
> /kind design
Adding the `--sleep` flag to the pod-template as its specified in the `values.yaml`
Fixes #
**Checklist**

Adding sleep flag to pod-template

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/templates/pod-template.tpl

Signed-off-by: Enoe Mugnaschi <enmuro@gmail.com>
/kind bug
> /kind design
Fixes #376 
**Checklist**

fix: falco helm chart priorityClassName on pod template

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/deployment-ui.yaml
falcosidekick/values.yaml

Signed-off-by: Thomas Labarussias <issif_github@gadz.org>
Co-authored-by: Travis Hansen <travisghansen@yahoo.com>
> /kind bug
> /kind design
/kind feature
Support storageEnabled for redis to allow ephemeral installs
Fixes # …

Support storageEnabled for redis to allow ephemeral installs

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/templates/certs-secret.yaml

```
```
/kind bug
> /kind design
This PR fixes the name of the falco secret that stores the certifcates. The secret was named using the just the falco `fullname` while the pod was expecting the falco `fullname` + the `-cert` suffix.
**Which …

fix(falco): fix name of the falco certs secret

---

falco/Chart.yaml
falco/ci/ci-values.yaml

/kind cleanup
update ci-values
Fixes #
**Checklist**

[Falco] update ci-values

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/ci/ci-values.yaml

/kind bug
cc @cpanato 
Fixes #
**Checklist**

update(falco/ci): fully disable the driver when running in CI

---

.circleci/install_tools.sh
falco-exporter/Chart.yaml
falco-exporter/templates/tests/test-connection.yaml
tests/e2e-kind.sh
tests/falco-test-ci.yaml

> /kind bug
> /kind design
Fixes #
**Checklist**

Install falco chart if there are changes in the falco-exporter

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/templates/daemonset.yaml
falco-exporter/values.yaml

> /kind bug
> /kind design
/kind feature
This PR adds support for configuring the falco-exporter DaemonSet updateStrategy, via a similar block as already exists for the falco DaemonSet.
The current falco-exporter chart does not support editing the default DaemonSet updateStrategy.
Fixes # …

add support for configuring the updateStrategy of the falco-exporter ds

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md

/kind feature
This PR bumps the Falco version to `0.32.2` and the chart version to `2.0.13`
**Checklist**

update: bump Falco to `0.32.2`

---

OWNERS

As we descussed in the last (September 7th 2022) Falco community call and given the positive feedback from other current mainteneirs I would like to propose myself as a reviewer.
Fixes #

update(OWNERS): add Aldo Lacuku (alacuku) to owners as reviewer

---

falco/CHANGELOG.md
falco/Chart.yaml

Signed-off-by: Eduardo Minguez <e.minguez@gmail.com>
/kind feature
The current sidekick dependency is too old
N/A
Fixes #
**Checklist**

Bump falcosidekick chart dependency to latest

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/rules/falco_rules.yaml
falco/rules/k8s_audit_rules.yaml
falco/templates/_helpers.tpl
falco/templates/pod-template.tpl
falco/values.yaml

> /kind bug
> /kind design
/kind feature
This PR updates the charts for the upcoming Falco version: 0.33.0. For more info, please check out the commits.
Fixes #404 
**Checklist**

support falco 0.33.0

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/values.yaml

> /kind bug
> /kind design
Fixes #
**Checklist**

chore(falco-exporter): bump falco-exporter to v.0.8.0

---

event-generator/CHANGELOG.md
event-generator/Chart.yaml
event-generator/generated/helm-values.md
event-generator/values.yaml

> /kind bug
> /kind design
Bump `event-generator version to v0.10.0`.
Furthermore,  changes the grpc socket path from `unix:///var/run/falco/falco.soc` to `unix:///run/falco/falco.sock`. Please note that this change is potentially a …

 update(event-generator): use the new grpc address introduced in falco 0.33.0

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/values.yaml

Fixes a spelling mistake found in the falco helm chart. 
Fixes #

docs: fix spelling mistake in falco/values.yaml

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
falco/generated/helm-values.md
falco/templates/_helpers.tpl
falco/templates/pod-template.tpl
falco/values-gvisor-gke.yaml
falco/values.yaml

Signed-off-by: Aldo Lacuku <aldo@lacuku.eu
> /kind bug
> /kind design
/kind feature
This PR adds support Falco+gVisor. People running gVisor-enabled kubernetes clusters can now deploy Falco using this chart.  For more info please have a look at the new config variables added for gVisor.
Furthemore, …

new: add support for Falco+gVisor

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/values.yaml

Signed-off-by: Mike Stewart <2521245+mike-stewart@users.noreply.github.com>
**What this PR does / why we need it**: Fixes a backwards comment in falco values.yaml.
**Which issue(s) this PR fixes**: Not logged.
**Checklist**

Fix comment in values.yaml

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/values.yaml

Signed-off-by: André Bauer <andre.bauer@staffbase.com>
/kind bug
* add toleration for "node-role.kubernetes.io/control-plane"
* on kubernetes 1.25 falco pod was not started on the master node as the node taint is now "node-role.kubernetes.io/control-plane" so the used toleration "node-role.kubernetes.io/master" did not fit
Fixes #
**Checklist**

add toleration for node-role.kubernetes.io/control-plane

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md

Signed-off-by: Luca Guerra <luca@guerra.sh>
Update the docs to include an example for running Falco on GKE, with or without gVisor.
Fixes #
**Checklist**
docs only

update(docs): add GKE (w/ or w/o gVisor) example

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/deployment-ui.yaml
falcosidekick/templates/deployment.yaml
falcosidekick/templates/secrets.yaml
falcosidekick/values.yaml

Co-authored-by: Lyonel Martinez <lyonel.martinez@numberly.com>
> /kind bug
> /kind design
/kind feature
Upgrade Falcosidekick chart to manage v2.27.0 of sidekick and v2.1.0 of UI
Fixes #
**Special notes for …

upgrade Falcosidekick chart to 0.5.10

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
tests/falco-test-ci.yaml

> /kind bug
> /kind design
Fix typo mentioning how to enable grpc.
Fixes #
**Checklist**

update(docs): fix typo on grpc notes

---

falco/CHANGELOG.md
falco/Chart.yaml

> /kind bug
> /kind design
/kind feature
Bump `falcosidekick` dependency to 0.5.10
Fixes #
**Checklist**

Bump falcosidekick dependency to 0.5.10

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/deployment-ui.yaml

/kind bug
> /kind design
Fix missing space in Falcosidekick-UI arguments
#441 
Fixes #
**Checklist**

Fix missing space in Falcosidekick-UI arguments

---

falco/CHANGELOG.md
falco/Chart.yaml

/kind bug
> /kind design
Bump `falcosidekick` dependency to 0.5.11
#441 
Fixes #
**Checklist**

Bump falcosidekick dependency to 0.5.11

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/deployment-ui.yaml

Signed-off-by: Jesús Carpintero <jesus.carpintero@gmail.com>
/kind bug
> /kind design
```sh
helm template falcosidekick falcosecurity/falcosidekick --set webui.enabled=true --set webui.ttl=3303
Error: YAML parse error on falcosidekick/templates/deployment-ui.yaml: error converting …
```

Fix missing space in Falcosidekick-UI ttl argument

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md
falco/templates/_helpers.tpl
falco/templates/pod-template.tpl
falco/values.yaml

/kind bug
> /kind design
/kind feature
Users are now allowed to set environments variables using dictionaries such as:
```
- name: myEnv
valueFrom:
fieldRef:
fieldPath: metadata.namespace
```
The previous solution required variables to be provided as key values:
```
- name: myEnv
value: myVar
``` …

fix(falco/env-variable): allow users to set env variables

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md

> /kind bug
> /kind design
Add a "warning" to better understand Falco kernel driver behavior to prevent spam issues.
Note that I want to add some more cohesive information, for example how to precheck if a prebuilt module is available and maybe a stronger note that out of box …

update(docs): clarify driver behavior for chart

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/tests/test-connection.yaml
falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
This adds the node selector, tolerations and affinity value options to the test-connection pod.
Fixes #
**Checklist**

new(falcosidekick): add nodeSelector, tolerations and affinity values for test connection pod

---

falco/CHANGELOG.md
falco/Chart.yaml

Signed-off-by: SEANDOUGHTY <sean@render.com>
> /kind bug
> /kind design
Fixes #
**Checklist**

update(falco) bump falcosidekick dependency to 0.5.16

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/generated/helm-values.md

> /kind bug
> /kind design
New chart release for falco `0.34.1`.
Fixes #
**Checklist**

update(falco): bump appVersion to Falco 0.34.1

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/README.md
falco/generated/helm-values.md

> /kind bug
> /kind design
This PR fixes the `k8saudit` config values in the docs.
Fixes #
**Checklist**

update(docs): correct k8saudit config values in README.md file

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md
falcosidekick/templates/deployment-ui.yaml
falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
allow to set `allowcors` in Falcosidekick-UI
Fixes #
**Checklist**

allow to set allowcors in Falcosidekick-UI

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/templates/grafana-dashboard.yaml
falco-exporter/values.yaml

> /kind bug
> /kind design
/kind feature
Adds the functionality to pack the dashboard into a folder. (Grafana Browser)
Fixes #
**Checklist**

Feat: Set grafana dashboard folder

---

falco/CHANGELOG.md
falco/Chart.yaml
falco/values-k8saudit.yaml

Fix typo in values-k8audit file

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/values.yaml

> /kind bug
> /kind design
/kind feature
Fixes #
**Checklist**

Bump Falco-exporter dependency to 0.8.2

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/values.yaml

> /kind bug
/kind cleanup
> /kind design
This adds an appropriate SecurityContext for Falco-exporter.
Fixes #425 
**Checklist**

fix(falco-expoter): added default securityContext

---

falco-exporter/CHANGELOG.md
falco-exporter/Chart.yaml
falco-exporter/README.md
falco-exporter/values.yaml

/kind feature
Falco exporter version upgrade to v0.8.3
**Checklist**

Bump Falco-exporter image version to 0.8.3

---

README.md

As per title.
Fixes #
**Checklist**

update(readme): link to website and main Falco repo

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.gotmpl
falcosidekick/README.md
falcosidekick/templates/deployment-ui.yaml
falcosidekick/templates/secrets-ui.yaml
falcosidekick/values.yaml

…2.2.0)░
> /kind bug
> /kind design
/kind feature
Fixes #
**Checklist**

update falcosidekick chart to 0.6.4 (upgrade of falcosidekick-ui to v2.2.0)

---

falco/.vscode/settings.json
falco/CHANGELOG.md
falco/Chart.yaml
falco/rules/twitter_rules.yaml
falco/values-twitter.yaml

> /kind bug
> /kind design
/kind feature
Fixes #
**Checklist**

update falco chart to 3.6.1

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/templates/secrets-ui.yaml

/kind bug
> /kind design
Fix wrong key used for the secret with the user credentials
#522 
Fixes #
**Checklist**

fix wrong key used for the user secret

---

falcosidekick/CHANGELOG.md
falcosidekick/Chart.yaml
falcosidekick/README.md

Fix typo in README.md

---

.github/workflows/test.yml

/kind bug
/kind cleanup
- should run for any PR
/assign @Issif @leogr @LucaGuerra 
Fixes #
**Checklist**

should run for any PR

---

charts/falco-exporter/CHANGELOG.md
charts/falco-exporter/Chart.yaml

- bump falco-exporter to test ci
Fixes #
**Checklist**

bump falco-exporter to test ci

---

charts/event-generator/CHANGELOG.md
charts/event-generator/Chart.yaml

> /kind bug
> /kind design
- bump event-generator
Fixes #
**Checklist**

bump event-generator

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml

> /kind bug
> /kind design
- bump falco
Fixes #
**Checklist**

bump falco

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml

- bump falcosidekick
Fixes #
**Checklist**

bump falcosidekick

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.gotmpl
charts/falcosidekick/README.md
charts/falcosidekick/templates/prometheusrule.yaml
charts/falcosidekick/templates/rbac.yaml
charts/falcosidekick/templates/secrets.yaml
charts/falcosidekick/templates/service.yaml
charts/falcosidekick/templates/servicemonitor.yaml
charts/falcosidekick/values.yaml

/kind bug
/kind cleanup
> /kind design
/kind feature
* Fix the behavior with the `AWS IRSA` with a new value `aws.config.useirsa`
* Add a section in the README to describe how to use a subpath for `Falcosidekick-ui` ingress
* Add a `ServiceMonitor` for prometheus-operator
* Add a `PrometheusRule` for …

add aws.config.useirsa to fix the behavior with AWS IRSA

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml

> /kind bug
> /kind design
/kind feature
Fixes #
**Checklist**

Upgrade falcosidekick chart to v0.7.6

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml

/kind feature
Upgrade Falco chart to target falcosidekick v0.7.7.
N/A
**Checklist**

Upgrade falcosidekick chart to v0.7.7

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/deployment.yaml

/kind bug
> /kind design
The chart can't be deployed anymore if the cert file is not provided
Fixes #
**Checklist**

fix the condition for the missing cert files

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml

Get ready for Falco 0.36.2.
Fixes #
**Checklist**

update(falco): bump chart and Falco version

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/_helpers.tpl
charts/falcosidekick/templates/aadpodidentity.yaml
charts/falcosidekick/templates/certs-secret.yaml
charts/falcosidekick/templates/clusterrole.yaml
charts/falcosidekick/templates/deployment-ui.yaml
charts/falcosidekick/templates/deployment.yaml
charts/falcosidekick/templates/ingress-ui.yaml
charts/falcosidekick/templates/ingress.yaml
charts/falcosidekick/templates/podsecuritypolicy.yaml
charts/falcosidekick/templates/prometheusrule.yaml
charts/falcosidekick/templates/rbac-ui.yaml
charts/falcosidekick/templates/rbac.yaml
charts/falcosidekick/templates/secrets-ui.yaml
charts/falcosidekick/templates/secrets.yaml
charts/falcosidekick/templates/service-ui.yaml
charts/falcosidekick/templates/service.yaml
charts/falcosidekick/templates/servicemonitor.yaml

Created from #563 I just update CHANGELOG and bump chart version
/kind cleanup
**Checklist**

Refactoring Kubernetes recommanded labels for Falco Sidekick

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md

**What this PR does / why we need it:**
Updates the link to the policy report output documentation

Fix README link to Policy Report documentation

---

.github/PULL_REQUEST_TEMPLATE.md

> /kind bug
> /kind design
Fixes #
**Checklist**

update(pull-request-template): add k8s-metacollector area

---

Makefile

/kind bug
> /kind design
Fix the `helm-deps-update` target.
Fixes #
**Checklist**

fix(makefile): correctly updted dependencies for each chart

---

charts/k8s-metacollector/CHANGELOG.md
charts/k8s-metacollector/Chart.yaml
charts/k8s-metacollector/README.gotmpl
charts/k8s-metacollector/README.md
charts/k8s-metacollector/tests/unit/serviceMonitorTemplate_test.go
charts/k8s-metacollector/values.yaml

> /kind bug
> /kind design
update(k8s-metacollector): lower interval and scrape_timeout values for service monitor.
Fixes #
**Checklist**

update(k8s-metacollector): lower interval and scrape_timeout values for service monitor

---

charts/k8s-metacollector/CHANGELOG.md
charts/k8s-metacollector/Chart.yaml
charts/k8s-metacollector/README.gotmpl
charts/k8s-metacollector/README.md
charts/k8s-metacollector/dashboards/k8s-metacollector-dashboard.json
charts/k8s-metacollector/templates/collector-dashboard-grafana.yaml
charts/k8s-metacollector/tests/unit/chartInfo.go
charts/k8s-metacollector/tests/unit/commonMetaFields_test.go
charts/k8s-metacollector/tests/unit/defaultResources_test.go
charts/k8s-metacollector/tests/unit/deploymentTemplate_test.go
charts/k8s-metacollector/tests/unit/grafanaDashboards_test.go
charts/k8s-metacollector/tests/unit/serviceAccountTemplate_test.go
charts/k8s-metacollector/tests/unit/serviceMonitorTemplate_test.go
charts/k8s-metacollector/tests/unit/serviceTemplate_test.go
charts/k8s-metacollector/values.yaml

> /kind bug
> /kind design
/kind feature
This PR adds the grafana dashboard for the `k8s-metacollector`. 
Fixes #
**Checklist**

add collector grafana dashboard

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

/kind bug
> /kind design
>/kind chart-release
Update README.md.
Fixes #
**Checklist**

fix(falco): update README.md

---

charts/event-generator/CHANGELOG.md
charts/event-generator/Chart.yaml
charts/event-generator/README.md

/kind bug
/kind cleanup
> /kind design
Update README.md.
Fixes #
**Checklist**

fix(event-generator): update README.md

---

.github/workflows/docs.yml

> /kind bug
> /kind design
/kind feature
This PR adds a new check in the CI that enforces the helm docs generation.
Fixes #
**Checklist**

new(CI): enforce the helm docs

---

.github/workflows/docs.yml
Makefile
charts/falco-exporter/CHANGELOG.md
charts/falco-exporter/Chart.yaml
charts/falco-exporter/README.gotmpl
charts/falco-exporter/README.md
charts/falco-exporter/values.yaml

> /kind bug
> /kind design
This PR updates the docs for falco-exporter and adds the helm docs for it. Configuration values are now generated started from the values.yaml file.
The falco-exporter chart was the last chart that …

falco-exporter update docs

---

README.md

> /kind bug
> /kind design
Update the contributing section.
Fixes #
**Checklist**

update(README.md): update contributing section

---

README.md

> /kind bug
/kind cleanup
> /kind design
Fixes link tags in README.md file.
Fixes #
**Checklist**

fix(readme): link tags

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/servicemonitor.yaml

/kind bug
> /kind design
The Falco service is not scrapped because of a mismatch of the labels for the selection
#648 
Fixes #
**Checklist**

fix the labels for the serviceMonitor of falcosidekick

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml

> /kind bug
> /kind design
/kind feature
#648 
Fixes #
**Checklist**

bump falcosidekick dependency version to v0.7.17 install latest version through falco chart

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

> /kind bug
> /kind design
/kind feature
bump falcosidekick dependency version to v0.7.19
Fixes #
**Checklist**
- [] Variables are documented in the README.md

bump falcosidekick dependency version to v0.7.19

---

charts/k8s-metacollector/CHANGELOG.md
charts/k8s-metacollector/Chart.yaml
charts/k8s-metacollector/README.md

> /kind bug
> /kind design
update(k8s-metacollector): bump application version to 0.1.1
https://github.com/falcosecurity/k8s-metacollector/issues/102
Fixes #
**Checklist**

update(k8s-metacollector): bump application version to 0.1.1

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

> /kind bug
> /kind design
update(falco): bump k8s-metacollector dependency version to v0.1.1
See: #682, https://github.com/falcosecurity/k8s-metacollector/issues/102
Fixes # …

update(falco): bump k8s-metacollector dependency version to v0.1.1

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/secrets.yaml

Use webui.service.port for WEBUI_URL secret value

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

> /kind bug
> /kind design
update(falco): bump falco version to 0.38.1
Fixes #
**Checklist**

update(falco): bump falco version to 0.38.1

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/secrets-ui.yaml

/kind bug
> /kind design
Fixes #
**Checklist**

Add a condition to create the secrets for the redis only if the webui is deployed

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

> /kind bug
> /kind design
/kind feature
Fixes #
**Checklist**

bump falcosidekick dependency to v0.8.* to match with future versions

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/values-k8saudit.yaml
charts/falco/values-syscall-k8saudit.yaml

/kind bug
> /kind design
Fixes #
**Checklist**

fix(falco): use rules_files key in the preset values files

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/values.yaml

/kind feature
See https://github.com/falcosecurity/falco/issues/3289
Fixes #
**Checklist**

update(falco): update chart to 4.8.0 for Falco 0.38.2

---

charts/k8s-metacollector/CHANGELOG.md
charts/k8s-metacollector/Chart.yaml
charts/k8s-metacollector/README.md
charts/k8s-metacollector/dashboards/k8s-metacollector-dashboard.json

/kind bug
> /kind design
Before PR:
After:
Fixes #
**Checklist**

[fix] Helm : Grafana dashboard for k8s metacollector

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

bump Falco chart version to 4.8.1 to fetch latest falcosidekick chart.
**Checklist**

chore(falcosidekick): bump Falco chart version to 4.8.1

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

> /kind bug
> /kind design
Fixes #
**Checklist**

update(falco): bump falco version to 0.39.1

---

.lycheeignore
charts/falco-talon/CHANGELOG.md
charts/falco-talon/Chart.yaml
charts/falco-talon/README.gotmpl
charts/falco-talon/README.md
charts/falco-talon/values.yaml

/kind cleanup
Fixes #
**Checklist**

falco-talon: remove all refs to the previous org

---

README.md

> /kind bug
> /kind design
Fixes #
**Checklist**

chore(readme): add falco-talon chart link to readme

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.gotmpl
charts/falco/README.md
charts/falco/values.yaml

> /kind bug
> /kind design
update(falco): bump falco version to 0.39.2 and falcoctl to 0.10.1
Fixes #
**Checklist**

update(falco): bump falco version to 0.39.2 and falcoctl to 0.10.1

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

> /kind bug
> /kind design
/kind feature
bump falcosidekick dependency to v0.9.* to match with future versions
Fixes #
**Checklist**

bump falcosidekick dependency to v0.9.* to match with future versions

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/secrets.yaml
charts/falcosidekick/values.yaml

/kind bug
> /kind design
```
* cannot parse 'Elasticsearch.Batching.BatchSize' as int: strconv.ParseInt: parsing "5.24288e+06": invalid syntax …
```

fix value conversions errors

---

charts/falco-talon/CHANGELOG.md
charts/falco-talon/Chart.yaml

/kind bug
> /kind design
/area falco-talon
Update the chart to use the latest version of talon with bug fixes
Fixes #
**Checklist**

update talon version to v0.2.1 for bug fixes

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/serviceMonitor.yaml
charts/falco/tests/unit/serviceMonitorTemplate_test.go

/kind bug
> /kind design
This PR fixes a bug that would not set the selector in the `serviceMonitor`
Fixes #
#790 
**Checklist**

fix service monitor selector

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/values-k8saudit.yaml
charts/falco/values-syscall-k8saudit.yaml

/kind bug
> /kind design
See https://github.com/falcosecurity/plugins/issues/550
Fixes https://github.com/falcosecurity/plugins/issues/550
**Checklist**

update(falco): bump k8saudit version in values-k8saudit.yaml

---

.github/PULL_REQUEST_TEMPLATE.md

> /kind bug
> /kind design
Fixed `/area` labels for consistency
Fixes #
**Checklist**

docs(.github): correct area labels

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.gotmpl
charts/falco/README.md
charts/falco/values.yaml

> /kind bug
> /kind design
Fixes #
**Checklist**

docs(falco/chart): update driver docs and fix broken links

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/_helpers.tpl
charts/falco/templates/configmap.yaml
charts/falco/templates/pod-template.tpl
charts/falco/tests/unit/containerEnginesConfiguration_test.go
charts/falco/values.yaml

> /kind bug
> /kind design
Fixes #
**Checklist**

falco 0.40.0

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

> /kind bug
> /kind design
Fixes #
**Checklist**

fix(falco): bump version to 0.40.0

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/secrets.yaml
charts/falcosidekick/values.yaml

> /kind bug
> /kind design
Upgrade falcosidekick to v2.31.0
Fixes #
**Checklist**

upgrade falcosidekick to v2.31.0

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml

> /kind bug
> /kind design
Fixes #
**Checklist**

upgrade falcosidekick to v2.31.1

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/values.yaml

/kind bug
> /kind design
Forgot to update the image tag in the last release.....
Fixes #
#833  …

upgrade falcosidekick to v2.31.1 (fix)

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/values.yaml

> /kind bug
> /kind design
Fixes #
**Checklist**

chore(falco): bump falcoctl to 0.11.0

---

charts/falco-talon/CHANGELOG.md
charts/falco-talon/Chart.yaml
charts/falco-talon/templates/deployment.yaml

/kind bug
> /kind design
/kind feature
/area falco-talon-chart
Update the version of talon
#820 
Fixes #
**Checklist**

bump up talon version to 0.3.0 + fix missing usage of imagePullSecrets

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md

/kind bug
> /kind design
Fix missing values in the readme
Fixes #
**Checklist**

fix missing values in the readme

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/deployment.yaml
charts/falcosidekick/values.yaml

> /kind bug
> /kind design
/kind feature
https://github.com/falcosecurity/falcosidekick/issues/1111#issuecomment-2640806867
Fixes #
I've already fixed the corrisponding …

add customtags

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/pod-template.tpl
charts/falco/tests/unit/containerEnginesMounts_test.go

/kind bug
> /kind design
This PR removes the `hardcoded` values for container engines in `volumeMounts` and uses the values from the values.yaml file instead.
#840
Fixes #
**Special notes …

fix container engines sockets

---

charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/values.yaml

> /kind bug
> /kind design
Fixes #
**Checklist**
- [ x ] Chart Version bumped
- [ x ] Variables are documented in the …

fix: disable Talon by default on Falco installation

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/templates/deployment-ui.yaml

/kind bug
K8S adds those fields by itself on apply, which ArgoCD sees as a diff after apply. We could ignore it, but there is little reason to omit those fields in the definition.
Fixes #
**Checklist**

fix: avoid ArgoCD diff on volumeClaimTemplates

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/templates/NOTES.txt
charts/falco/templates/pod-template.tpl

/kind bug
> /kind design
Fixes #875
**Checklist**

fix falcoctl config

---

charts/falco/BREAKING-CHANGES.md
charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/values.yaml

> /kind bug
> /kind design
Fixes #
**Checklist**

feat: bump talon to 0.3.0, rename talon subchart to follow standard

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md
charts/falco/tests/unit/containerPlugin/containerPluginConfig_test.go
charts/falco/tests/unit/k8smetaPlugin/k8smetacollectorDependency_test.go
charts/falco/values.yaml

> /kind bug
> /kind design
Fixes #
**Checklist**

update(charts/falco): bump to Falco 0.41.2

---

OWNERS

> /kind bug
> /kind design
Hi folks!
Encouraged by @leogr, I would like to propose myself as maintainer of this repo.
Fixes #
**Checklist**

vote: docs(OWNERS): add `ekoops` as approver

---

charts/falcosidekick/CHANGELOG.md
charts/falcosidekick/Chart.yaml
charts/falcosidekick/README.md
charts/falcosidekick/templates/secrets.yaml
charts/falcosidekick/values.yaml

/kind feature
Add Splunk output
Fixes https://github.com/falcosecurity/falcosidekick/issues/1227
**Checklist**

feat: add Splunk output

---

charts/falco/CHANGELOG.md
charts/falco/Chart.yaml
charts/falco/README.md

> /kind bug
> /kind design
/kind feature
**What this PR does / why we need it**: Bumps the falco chart dep for the falcosidekick chart from 0.9.X to 0.11.X.
N/A
**Checklist**

chore: bump falcosidekick dep in falco chart to 0.11.X
